name: trips_simulator
description: "Projeto de simulação para viagens. - Teste Fretadão"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  go_router: ^17.0.1
  http: ^1.6.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - config/envs/.env
